-- Migration 003: Create properties table
CREATE TABLE IF NOT EXISTS properties (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agency_id         UUID NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
    created_by        UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title             VARCHAR(255) NOT NULL,
    description       TEXT,
    type              VARCHAR(30) NOT NULL CHECK (type IN ('apartment', 'house', 'land', 'commercial', 'garage', 'other')),
    transaction_type  VARCHAR(20) NOT NULL CHECK (transaction_type IN ('sale', 'rent')),
    price             DECIMAL(12, 2),
    surface_area      DECIMAL(8, 2),
    rooms             INTEGER,
    bedrooms          INTEGER,
    bathrooms         INTEGER,
    floor             INTEGER,
    total_floors      INTEGER,
    construction_year INTEGER,
    has_parking       BOOLEAN DEFAULT FALSE,
    has_balcony       BOOLEAN DEFAULT FALSE,
    has_garden        BOOLEAN DEFAULT FALSE,
    is_furnished      BOOLEAN DEFAULT FALSE,
    is_available      BOOLEAN DEFAULT TRUE,
    status            VARCHAR(30) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'under_offer', 'sold', 'rented', 'withdrawn')),
    address           TEXT NOT NULL,
    city              VARCHAR(100) NOT NULL,
    postal_code       VARCHAR(10),
    latitude          DECIMAL(9, 6),
    longitude         DECIMAL(9, 6),
    created_at        TIMESTAMP DEFAULT NOW(),
    updated_at        TIMESTAMP DEFAULT NOW()
);
